version: 2.1 # use CircleCI 2.1
jobs: # A basic unit of work in a run
  build: # runs not using Workflows must have a `build` job as entry point
    # directory where steps are run
    working_directory: ~/repo
    docker: # run the steps with Docker
      # CircleCI Python images available at: https://hub.docker.com/r/circleci/python/
      - image: continuumio/conda-ci-linux-64-python3.10
        environment: # environment variables for primary container
          PIPENV_VENV_IN_PROJECT: true
    steps: # steps that comprise the `build` job
      - checkout # check out source code to working directory
      - run: 
          command: |
            conda create -n tbtamr python=3.10
            source activate tbtamr
            python3 setup.py sdist bdist_wheel
            pip3 install dist/tbtamr-*-py3-none-any.whl 
            tbtamr --help
            pytest
      
     
      - store_test_results: # Upload test results for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
          path: test-results
      - store_artifacts: # Upload test summary for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
          path: test-results
destination: tr1
